# Numpy

In [1]:
#Numpy is most suitable for performing basic numerical computations such as mean, median, range, etc. Alongside, it also supports the creation of multi-dimensional arrays.
import numpy as np
import random

In [42]:
#convert list to numpy arrays-1D 
my_list = [1,2,3,3,5]
arr = np.asarray(my_list)

#create an array of even space between the given range of values
print(np.linspace(0, 1, 5))

print(my_list)
print(arr)
print(type(my_list),type(arr),arr.dtype)
print(arr.shape)

[0.   0.25 0.5  0.75 1.  ]
[1, 2, 3, 3, 5]
[1 2 3 3 5]
<class 'list'> <class 'numpy.ndarray'> int64
(5,)


In [8]:
#convert list to numpy arrays-multiD
my_list = [[1,2,4],[2,4,5]]
arr = np.asarray(my_list)
print(my_list)
print(arr)
print(type(my_list),type(arr),arr.dtype)
print(arr.shape)

[[1, 2, 4], [2, 4, 5]]
[[1 2 4]
 [2 4 5]]
<class 'list'> <class 'numpy.ndarray'> int64
(2, 3)


In [18]:
#create new numpy Arrays
arr0 = np.zeros((2,3),dtype='uint8') #size is given through tuples and initially float, typecast it
print(arr0)

[[0 0 0]
 [0 0 0]]


In [13]:
# Identity Matrix
I = np.eye(5)*5
print(I)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


In [21]:
# all ones
O = np.ones((5,5))
print(O)
print("-"*30)
# array copies
arr1 = O.copy()
print(arr1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
------------------------------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
# Shapes of numpy arrays and multi-dimensional arrays
my_list = [[1,2,4],[2,4,5]]
arr = np.asarray(my_list)

arr1 = arr.reshape(3,2)
print(arr1)

[[1 2]
 [4 2]
 [4 5]]


In [25]:
arr1 = arr.reshape(3,2,1)
print(arr1)

[[[1]
  [2]]

 [[4]
  [2]]

 [[4]
  [5]]]


In [26]:
arr1 = arr.reshape(3,-1)
print(arr1)

[[1 2]
 [4 2]
 [4 5]]


In [31]:
# Random numpy arrays
r_arr = np.random.random((5,5))
print(r_arr)
print("-"*30)
print(np.mean(r_arr,axis=1))
print(np.mean(r_arr,axis=0))

[[0.01072858 0.31523738 0.82247578 0.40429174 0.10409665]
 [0.75072654 0.30745507 0.18828453 0.70122944 0.1922173 ]
 [0.63651352 0.29512466 0.41258704 0.14276637 0.40433074]
 [0.85844233 0.46257035 0.38144881 0.655621   0.27093957]
 [0.96780174 0.76465621 0.37331425 0.10994762 0.09559972]]
------------------------------
[0.33136603 0.42798258 0.37826447 0.52580441 0.46226391]
[0.64484254 0.42900873 0.43562208 0.40277123 0.2134368 ]


In [35]:
# transpose of a matrix
r_arr = np.random.random((5,5))
print(r_arr)
print("-"*30)
r_arr2 = r_arr.transpose()
print(r_arr2)

[[0.87953024 0.66560569 0.7488362  0.34620965 0.8697888 ]
 [0.77609715 0.11641265 0.31438315 0.95017497 0.10583084]
 [0.26879433 0.41216473 0.99659183 0.06217917 0.8365668 ]
 [0.2063188  0.02790068 0.14751995 0.73736694 0.68108578]
 [0.79909024 0.59818095 0.27277513 0.72729004 0.63796433]]
------------------------------
[[0.87953024 0.77609715 0.26879433 0.2063188  0.79909024]
 [0.66560569 0.11641265 0.41216473 0.02790068 0.59818095]
 [0.7488362  0.31438315 0.99659183 0.14751995 0.27277513]
 [0.34620965 0.95017497 0.06217917 0.73736694 0.72729004]
 [0.8697888  0.10583084 0.8365668  0.68108578 0.63796433]]


In [36]:
# randint function
B = np.random.randint(low=-5, high=10, size=(3, 3))
print(B)

[[ 3 -1 -4]
 [-2 -5  7]
 [ 7 -3  1]]


In [37]:
# change dtype of numpy array
A = np.array([[1, 2, 3], [-1, 0, 5], [9, 7, 2]])
print(A,A.dtype)
print('-'*40)
A = A.astype(np.float16)
print(A, A.dtype)

[[ 1  2  3]
 [-1  0  5]
 [ 9  7  2]] int64
----------------------------------------
[[ 1.  2.  3.]
 [-1.  0.  5.]
 [ 9.  7.  2.]] float16


In [39]:
cc = np.concatenate((A.reshape(3,3,1),B.reshape(3,3,1)),axis=2)
print (cc,cc.shape)

[[[ 1.  3.]
  [ 2. -1.]
  [ 3. -4.]]

 [[-1. -2.]
  [ 0. -5.]
  [ 5.  7.]]

 [[ 9.  7.]
  [ 7. -3.]
  [ 2.  1.]]] (3, 3, 2)


In [43]:
# if you are required to combine a 2D array with 1D array,then use h_stack and v_stack instead of concatenate
x = np.array([1,2,3])
grid = np.array([[4,5,6],[7,8,9]])
np.vstack([x,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
# we can split the arrays based on pre-defined positions
arr = np.array([1,2,3,4,4,5,5,6,7])
x1,x2,x3 = np.split(arr,[3,6]) # 3 pieces,then 6-3 pieces
print(x1,x2,x3)
print('*'*30)
x = np.arange(8.0)
np.split(x, [3, 5, 6, 10])

[1 2 3] [4 4 5] [5 6 7]
******************************


[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

In [6]:
#multiply two arrays (doubt)
x1 = np.arange(9.0).reshape(3,3)
print(x1)
x2 = np.arange(3.0)
print(x2)
np.multiply(x1,x2)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[0. 1. 2.]


array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [ ]:
# inverse
C = np.random.random((4, 6))
C_inv = np.linalg.pinv(C)
print (C_inv.dot(C))

In [ ]:
# Read about SVD and pseudo-inverse
